### PR TITLE
Convert reports to JSON

### LINKED ISSUE #133: Problem in sending error report using Stacktrace.report
I am using express 4.0 and I'm trying to send client side error from my angular app to server. I have exposed StackTrace as an angular service stacktraceService.

If I catch the error manually, and send them via a POST request like this:

         stacktraceService.StackTrace
            .fromError(exception)
            .then(function(stackframes){
                console.log(stackframes);
                $.ajax({
                    type: "POST",
                    url: "./error",
                    contentType: "application/json",
                    data: angular.toJson({
                        stack: stackframes
                    })
                });
            });

The server side code can parse the req.body using "json()" method of express/body-parser and show it correctly.

However, if I use the stacktrace.js report functionality, like,

          stacktraceService.StackTrace
            .fromError(exception)
            .then(function(stackframes){
                console.log(stackframes);
                stacktraceService.StackTrace
                .report(stackframes, './error');
            });

,then the server side code finds the req.body undefined.

I was wondering what the cause would be. Am I using .report() functionality wrong?

### PR DESCRIPTION
**Pull request by oliversalzburg**
Includes JSON3 in the polyfill version
Fixes #133

### CODE REVIEW

**Comment by oliversalzburg** [comment]
@eriwen Can we exclude `dist` from HoundCI checks? Also, do you know what the problem is with Travis?

**Comment by eriwen** [comment]
@oliversalzburg Looks like we can exclude files from Hound by adding a .jshintignore file with the following content: 

```
dist/*
```

I'm not sure about Travis. It works on master and we haven't made changes. Maybe something is wrong with the PR-specific config somehow...

**Comment by eriwen** [comment]
Also, this looks good; thank you!

File: gulpfile.js [hunk 1]
```diff
@@ -15,7 +15,8 @@ var polyfills = [
 var dependencies = [
     './node_modules/stacktrace-gps/dist/stacktrace-gps.min.js',
     './node_modules/stack-generator/dist/stack-generator.js',
-    './node_modules/error-stack-parser/dist/error-stack-parser.js'
+    './node_modules/error-stack-parser/dist/error-stack-parser.js',
+    './node_modules/json3/lib/json3.js'
```
Comment (eriwen) [inline gulpfile.js]: This should go in `polyfills`

**Comment by oliversalzburg** [comment]
- Fixed the gulp build (wow, what a mistake)
- Added `.jshintignore`
- Fixed the test

File: spec/stacktrace-spec.js [hunk 2]
```diff
@@ -230,7 +230,8 @@ describe('StackTrace', function () {
             });
             waits(100);
             runs(function () {
-                expect(server.requests[0].requestBody).toEqual({stack: stackframes});
+                var expectedResponse = JSON.stringify({stack: stackframes});
+                expect(server.requests[0].requestBody).toEqual(expectedResponse);
```
Comment (oliversalzburg) [inline spec/stacktrace-spec.js]: How can that still be too long? O_o

Comment (eriwen) [inline spec/stacktrace-spec.js]: Hm.. I'm guessing the default line length limit is 80. 

Sorry about the annoying Hound stuff; don't worry about this kinda thing. I may just disable it since JSHint is part of the build anyway.

**Comment by eriwen** [comment]
Looks good! :shipit:
